GhcEnableTablesNextToCode = NO
INTEGER_LIBRARY           = integer-simple
SRC_HC_OPTS               = -O -H64m
GhcStage1HcOpts           = -O
GhcStage2HcOpts           = -O2
GhcLibHcOpts              = -O2
BUILD_PROF_LIBS           = NO
SplitObjs                 = NO
SplitSections             = NO
BUILD_SPHINX_HTML         = NO
BUILD_SPHINX_PDF          = NO
HADDOCK_DOCS              = YES
EXTRA_HADDOCK_OPTS        += --quickjump --hyperlinked-source
